SYMBOL = "XAUUSD"

M15_BARS = 50
H1_BARS = 100

M15_TIMEFRAME_NAME = "M15"
H1_TIMEFRAME_NAME = "H1"

EMA_FAST = 20
EMA_SLOW = 50

RSI_PERIOD = 14
ATR_PERIOD = 14

STATUS_NO_TRADE = "NO TRADE"
STATUS_BUY_WATCH = "BUY WATCH"
STATUS_SELL_WATCH = "SELL WATCH"
STATUS_READY_BUY = "READY BUY"
STATUS_READY_SELL = "READY SELL"

SIGNAL_WEAK = "WEAK"
SIGNAL_MEDIUM = "MEDIUM"
SIGNAL_STRONG = "STRONG"

FINAL_SIGNAL_BUY = "BUY"
FINAL_SIGNAL_SELL = "SELL"
FINAL_SIGNAL_WAIT = "WAIT"

SIGNAL_MODE_AGGRESSIVE = "aggressive"
SIGNAL_MODE_NORMAL = "normal"
SIGNAL_MODE_CONSERVATIVE = "conservative"

SIGNAL_MODE = SIGNAL_MODE_NORMAL

TELEGRAM_BOT_TOKEN = "8742400063:AAHH-bYUko5CClbeAsX-avkeoG_afHxIec0"
TELEGRAM_CHAT_ID = "6798132226"
ENABLE_TELEGRAM_NOTIFICATIONS = True

ENABLE_AUTO_TRADE = False
LOT_SIZE = 0.01
MAGIC_NUMBER = 20260316